---
title: "Clean LENA Data"
output: html_notebook
---

##Load data
```{r load_data}
library(tidyverse)
library(lubridate)
library(hms)

#daily files
#lena_daily_file_1 <- "~/Desktop/BABIES/r01_winter_2019/data/LENA Export (Daily) 20180316 154518.csv"
lena_daily_FQ_file_1 <- "~/Desktop/lena_18mo_symptoms/Data/LENA Export (Daily) 20180316 154518_ALL.csv"

#lena_daily_file_2 <- "~/Desktop/BABIES/r01_winter_2019/data/LENA Export (Daily) 20181128 153328.csv"
lena_daily_file_2 <- "~/Desktop/lena_18mo_symptoms/Data/LENA Export (Daily) 20181128 153328.csv"
lena_daily_file_3 <- "~/Desktop/lena_18mo_symptoms/Data/LENAExport_Daily_new_20190206.csv"

#5-minute files
#lena_5min_file_1 <- "~/Desktop/BABIES/r01_winter_2019/data/LENAExport_5Minute_20181220.csv"
lena_5min_file_1 <- "~/Desktop/lena_18mo_symptoms/Data/LENAExport_5Minute_20181220.csv"
lena_5min_file_2 <- "~/Desktop/lena_18mo_symptoms/Data/LENAExport_5Minute_new_20190204.csv"


#lena_5min_files_2 <- "~/Desktop/BABIES/r01_winter_2019/data/individual_5min"
lena_5min_files_2 <- "~/Desktop/lena_18mo_symptoms/Data/individual_5min_lsk_format"

lena_followup_long_file <- "~/Desktop/lena_18mo_symptoms/Data/lena_followup_long_20190216.csv"
lena_followup_cs_file <- "~/Desktop/lena_18mo_symptoms/Data/lena_followup_cs_20190216.csv"

lena_5min_files_df <-
  tibble(
    path = 
      list.files(
        path = lena_5min_files_2,
        all.files = TRUE,
        #pattern = "^LENA Export (5 Minute) \\d{3}_\\d{6}.csv$",
        no.. = TRUE,
        full.names = TRUE
      )
  ) %>% 
  filter(
    str_detect(path, "/.DS_Store") == FALSE
  )
```
# Daily data

## Read in daily data 
```{r}
#do we care about AVA_AvgScore if only 1 ps has it, and SS_StdScore if that's a snapshot??
lena_daily <-
  read_csv(lena_daily_FQ_file_1) %>% 
  mutate(
    Lastname = as.integer(Lastname),
    Birthdate = as.character(Birthdate),
    Timestamp = as.character(Timestamp),
    SS_DevAge = as.character(SS_DevAge),
    SS_StdScore = as.character(SS_StdScore),
    AVA_AvgScore = as.character(AVA_AvgScore)
  ) %>% 
  bind_rows(
    read_csv(lena_daily_file_2) %>% 
      mutate(
        Lastname = as.integer(Lastname),
        Birthdate = as.character(Birthdate),
        Timestamp = as.character(Timestamp),
        SS_DevAge = as.character(SS_DevAge),
        SS_StdScore = as.character(SS_StdScore),
        AVA_AvgScore = as.character(AVA_AvgScore)
      )
  ) %>% 
  select(
    -Type,
    -ChildKey,
    -Id,
    -Age,
    ID = Lastname,
    dob = Birthdate
  ) %>% 
  mutate(
    ID = as.numeric(ID),
    dob = parse_date(dob, format = "%Y-%m-%d"),
    Timestamp = parse_date(Timestamp, format = "%Y-%m-%d"),
    age = (dob %--% Timestamp) / months(1)
  ) %>% 
  select(
    -dob
  )
```


## Clean and wrangle daily data
```{r clean}
lena_daily <- 
  lena_daily %>%
  filter(!is.na(ProcessingFile)) %>% 
  group_by(ID) %>% 
  mutate(
    duration = as.numeric(
      as.duration(hms(Duration)),
      "hours"
    )
  ) %>% 
  filter(duration >= 8) %>% 
  mutate(
    day_type = wday(Timestamp),
    day_type = if_else(day_type == 1 | day_type == 7, "weekend", "weekday"),
    TV.Pct = as.integer(str_replace(TV.Pct, "%", "")),
    AWC_rate = AWC.Actual/duration,
    CTC_rate = CTC.Actual/duration,
    CVC_rate = CVC.Actual/duration
  ) %>%
  ungroup() %>% 
  select(
    ID,
    age,
    timestamp = Timestamp,
    day_type,
    duration,
    AWC_rate,
    CTC_rate,
    CVC_rate,
    TV.Pct
  ) 
```

```{r}
lena_daily_cl <- 
  lena_daily %>% 
  filter(age >= 5 & age <= 8) %>% 
  arrange(ID, timestamp) %>% 
  group_by(ID) %>% 
  mutate(
    day = 1:n()
  ) %>% 
  ungroup()
```

```{r}
lena_daily_cl %>% 
  count(day)

lena_daily_day1_rename <-
  lena_daily_cl %>% 
  filter(day == 1) %>% 
  rename_at(
    vars(timestamp, TV.Pct, AWC_rate, CTC_rate, CVC_rate, duration),
    funs(paste0(., "_D1"))
  ) %>% 
  select(-day)

lena_daily_day2_rename <-
  lena_daily_cl %>% 
  filter(day == 2) %>% 
  rename_at(
    vars(timestamp, TV.Pct, AWC_rate, CTC_rate, CVC_rate, duration),
    funs(paste0(., "_D2"))
  ) %>% 
  select(-day)

lena_daily_cl_wf <-
  lena_daily_day1_rename %>% 
  left_join(lena_daily_day2_rename, by = "ID")

cor.test(lena_daily_cl_wf$CTC_rate_D1, lena_daily_cl_wf$CTC_rate_D2)
```

#reformat sp 5 min data
```{r}
lena_5min_sp <-
  read_csv(lena_5min_file_2) %>% 
  mutate(
    ExternalReferenceID = as.integer(ExternalReferenceID),
    Recording_DOB = as.character(Recording_DOB),
    StartTime = as.character(StartTime)
  ) %>% 
  select(
    ExternalReferenceID,
    Recording_DOB,
    StartTime,
    Duration_Secs,
    AWC_COUNT,
    CT_COUNT,
    CV_COUNT,
    Recording_Gender,
    Meaningful,
    Distant, 
    TV_Elec,
    Overlap,
    Noise,
    Silence
  ) %>% 
  mutate(
    ID = ExternalReferenceID,
    dob = Recording_DOB,
    AWC.Actual = AWC_COUNT,
    CTC.Actual = CT_COUNT,
    CVC.Actual = CV_COUNT,
    Sex = Recording_Gender,
    Duration = as.hms(Duration_Secs),
    Meaningful = as.hms(Meaningful),
    Distant = as.hms(Distant),
    TV = as.hms(TV_Elec),
    Overlap = as.hms(Overlap),
    Noise = as.hms(Noise),
    Silence = as.hms(Silence),
    Timestamp = StartTime
  ) %>% 
  select(
    -ExternalReferenceID,
    -Recording_DOB,
    -Recording_Gender,
    -CT_COUNT,
    -CV_COUNT,
    -AWC_COUNT,
    -Duration_Secs
  )
```

# Read in 5-minute data 
```{r warning=FALSE}
lena_5min <-
  read_csv(lena_5min_file_1) %>% 
  mutate(
    Birthdate = as.character(Birthdate),
    Timestamp = as.character(Timestamp),
    Meaningful = as.hms(Meaningful)
  ) %>% 
  select(
    -Type,
    -ChildKey,
    -Id,
    -Age,
    -AVA_StdScore:-AVA_AvgScore_Pct,
    -Firstname,
    ID = Lastname,
    dob = Birthdate
  ) %>% 
  bind_rows(
    lena_5min_sp
  ) %>% 
  separate(Timestamp, into = c("date_record", "time_record"), sep = " ") %>% 
  mutate(
    ID = as.numeric(ID),
    dob = parse_date_time(dob, c("ymd", "mdy")),
    date_record = parse_date_time(date_record, c("ymd", "mdy")),
    age = (dob %--% date_record) / months(1)
  ) %>% 
  select(
    -dob
  )
```

```{r warning=FALSE}
lena_5min2 <-
  lena_5min_files_df %>%
  mutate(
    data = map(
      path, 
      read_csv, 
      col_names = TRUE,
      col_types = 
        list(
          Firstname = col_character(),
          Birthdate = col_character(),
          Timestamp = col_character(),
          AVA_StdScore = col_character(),
          Sex = col_character(),
          ChildKey = col_character()
        )
      )
  ) %>% 
  unnest(data) %>% 
  select(-path) %>% 
  mutate(
    Birthdate = as.character(Birthdate),
    Timestamp = as.character(Timestamp)
  ) %>% 
  select(
    -Type,
    -ChildKey,
    -Id,
    -Age,
    -AVA_StdScore:-AVA_AvgScore_Pct,
    ID1 = Firstname,
    ID2 = Lastname,
    dob = Birthdate
  ) %>% 
  separate(Timestamp, into = c("date_record", "time_record"), sep = " ") %>% 
  mutate(
    ID = as.numeric(
      if_else(
        is.na(ID2),
        ID1, ID2
      )
    ),
    dob = parse_date_time(dob, c("ymd", "mdy")),
    date_record = parse_date_time(date_record, c("ymd", "mdy")),
    age = (dob %--% date_record) / months(1)
  ) %>% 
  select(
    ID,
    everything(),
    -ID1,
    -ID2,
    -dob
  )
```

```{r}
lena_5min <-
  lena_5min %>% 
  bind_rows(lena_5min2) %>% 
  arrange(ID)
```

## Clean and wrangle 5-minute data
```{r}
lena_5min_cl <- 
  lena_5min %>% 
  group_by(ID) %>% 
  mutate(
    duration = as.numeric(
      as.duration(hms(as.numeric(Duration))),
      "hours"
    )
  ) %>% 
  group_by(ID, date_record, age) %>% 
  summarise(
    duration = sum(duration),
    awc_speech = sum(AWC.Actual >= 1),
    ctc_speech = sum(CVC.Actual >= 1)
  ) %>% 
  mutate(
    awc_prop = (awc_speech) / ((duration * 60) / 5), #proportion of 5 minute segments with AWC
    ctc_prop = (ctc_speech) / ((duration * 60) / 5) #proportion of 5 minute segments with CTC 
  ) %>% 
  filter(
    (age >= 5 & age <= 8),
    duration >= 8
  ) %>% 
  group_by(ID) %>% 
  mutate(
    day_type = wday(date_record),
    day_type = if_else(day_type == 1 | day_type == 7, "weekend", "weekday"),
    day = 1:n()
  ) %>% 
  ungroup()
```

```{r}
lena_5min_cl %>% 
  count(day)

lena_5min_day1_rename <-
  lena_5min_cl %>% 
  filter(day == 1) %>% 
  rename_at(
    vars(date_record:day_type),
    funs(paste0(., "_D1"))
  ) %>% 
  select(-day)

lena_5min_day2_rename <-
  lena_5min_cl %>% 
  filter(day == 2) %>% 
  rename_at(
    vars(date_record:day_type),
    funs(paste0(., "_D2"))
  ) %>% 
  select(-day)

lena_5min_cl_wf <-
  lena_5min_day1_rename %>% 
  left_join(lena_5min_day2_rename, by = "ID") %>% 
  mutate(
    #day_type_D1 = wday(date_record_D1),
    #day_type_D1 = if_else(day_type_D1 == 1 | day_type_D1 == 7, "weekend", "weekday"),
    #day_type_D2 = wday(date_record_D2),
    #day_type_D2 = if_else(day_type_D2 == 1 | day_type_D2 == 7, "weekend", "weekday")
  )

lena_5min_cl_wf %>% 
  filter(
    awc_prop_D1 > .2,
    awc_prop_D2 > .2
    ) %>% 
  ggplot(aes(awc_prop_D1, awc_prop_D2)) +
  geom_point() +
  geom_smooth(method = "lm")

glimpse(lena_5min_cl_wf)
```

```{r}
lena_5min_cl_wf %>% 
  summarise_at(
    vars(awc_prop_D1, ctc_prop_D1),
    funs(min, max, mean, sd), na.rm = TRUE
  )
```
#read in LENA follow up data
```{r}
lena_followup <-
  read_csv(lena_followup_long_file) %>% 
  rename(ID = record_id) %>% 
  mutate(ID = as.integer(ID)) %>% 
  bind_rows(
    read_csv(lena_followup_cs_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID))
  ) %>% 
  filter(
    lena_day_1_followup_questions_complete == 2 | lena_day_2_followup_questions_complete == 2
  ) %>% 
  mutate(
    lena_weekend = lena_daytype
  )

#t-test weekday vs. weekend and percent of time spent w mom
t.test(percent_mother ~ lena_weekend, data = lena_followup)
```

```{r}
lena_mal <- 
  lena_daily_cl_wf %>% 
  left_join(lscr_T1lg_6mocs, by = "ID") %>% 
  left_join(demo, by = "ID") %>% 
  left_join(crisys_wf, by = "ID")


t.test(sixmonth_crisys_win ~ maltreated, data = lena_mal)

glimpse

lena_mal %>% 
  filter(!is.na(maltreated)) %>% 
  group_by(maltreated) %>% 
  summarise_at(
    vars(AWC_rate_D1, AWC_rate_D2, CTC_rate_D1, CTC_rate_D2, CVC_rate_D1, CVC_rate_D2, age.x),
    funs(mean, sd), na.rm = TRUE
  )

t.test(AWC_rate_D1 ~ male, data = lena_mal)
t.test(CTC_rate_D1 ~ maltreated, data = lena_mal)

sy

lena_mal <- 
  lena_5min_cl_wf %>% 
  left_join(lscr_T1lg_6mocs, by = "ID")

lena_mal %>% 
  filter(!is.na(maltreated)) %>% 
  group_by(maltreated) %>% 
  summarise_at(
    vars(awc_prop_D1, ctc_prop_D1),
    funs(mean, sd), na.rm = TRUE
  )

t.test(awc_prop_D1 ~ maltreated, data = lena_mal)

glimpse(lena_mal)


glimpse(lena_mal)
```


