---
title: "BABIES demographic data"
author: "Lucy King"
date: "11/27/2018"
output: html_document
---

```{r}
##Libraries
library(tidyverse)
library(lubridate)
library(readr)

##Parameters
#demo_cs_file <- "~/Desktop/BABIES/r01_winter_2019/data/cs_demo_20181128.csv"
demo_cs_file <- "~/Desktop/lena_18mo_symptoms/Data/demo_cs_20190131.csv"

#demo_long_file <- "~/Desktop/BABIES/r01_winter_2019/data/long_demo_20181128.csv"
demo_mom_long_file <- "~/Desktop/lena_18mo_symptoms/Data/demo_long_preg_20190131.csv"
demo_baby_long_file <- "~/Desktop/lena_18mo_symptoms/Data/demo_long_nb_20190413.csv"

#dob_cs_file <- "~/Desktop/BABIES/r01_winter_2019/data/cs_dob_20181128.csv"
dob_cs_file <- "~/Desktop/lena_18mo_symptoms/Data/dob_cs_20190131.csv"
#dob_long_file <- "~/Desktop/BABIES/r01_winter_2019/data/long_dob_20181128.csv"
dob_long_file <- "~/Desktop/lena_18mo_symptoms/Data/dob_long_20190413.csv"

#visit_date_cs_file <- "~/Desktop/BABIES/r01_winter_2019/data/cs_visit_date_20181128.csv"
visit_date_cs_file <- "~/Desktop/lena_18mo_symptoms/Data/visit_date_cs_20190131.csv"
#visit_date_long_6mo_file <- "~/Desktop/BABIES/r01_winter_2019/data/long_6mo_visit_date_20181128.csv"
visit_date_long_6mo_file <- "~/Desktop/lena_18mo_symptoms/Data/visit_date_long_6mo_20190413.csv"
#visit_dates_long_t1t2_file <- "~/Desktop/BABIES/r01_winter_2019/data/long_t1t2_dates_20181128.csv"

##To get the following file, first need to run long_t1t2dates_combine.Rmd
visit_dates_long_t1t2_file <- "~/Desktop/lena_18mo_symptoms/Data/long_t1t2_dates_20190413.csv"

```
#get baby race and ethnicity (workaround for full script w dates not working)
```{r}
baby_raceth <-
  read_csv(demo_cs_file) %>% 
  select(
    ID = record_id,
    child_race,
    childrace_describe,
    child_ethnicity
  ) %>% 
  mutate(
    ID = as.integer(ID)
  ) %>% 
  bind_rows(
    read_csv(demo_baby_long_file) %>% 
      select(
        ID = record_id,
        child_race = baby_race,
        childrace_describe = baby_race_describe,
        child_ethnicity = baby_ethnicity
      ) %>% 
      mutate(
        ID = as.integer(ID)
      )
  )

write_csv(baby_raceth, "~/Desktop/lena_18mo_symptoms/Data/baby_race_ethnicity.csv")
```

```{r}
##Read in and join data 
dates <-
  read_csv(dob_cs_file) %>% 
  select(
    ID = record_id,
    mom_dob,
    baby_dob,
    baby_due_date,
    baby_sex
  ) %>% 
  mutate(
    ID = as.integer(ID)
  ) %>% 
  bind_rows(
    read_csv(dob_long_file) %>% 
      select(
        ID = record_id,
        mom_dob,
        baby_dob,
        baby_due_date
      ) %>% 
      mutate(
        ID = as.integer(ID)
      )
  ) %>% 
  left_join(
    read_csv(visit_date_cs_file) %>% 
      select(
        record_id,
        crf_date
      ) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      bind_rows(
        read_csv(visit_date_long_6mo_file) %>%
          mutate(crf_date = as.Date(crf_date, "%m/%d/%y")) %>%
          select(
            record_id,
            crf_date
          ) %>% 
          rename(ID = record_id) %>% 
          mutate(ID = as.integer(ID))
      )
  ) %>% 
  left_join(
    read_csv(
      visit_dates_long_t1t2_file) %>%
      mutate(ID = as.integer(ID)),
    by = "ID"
  ) %>% 
  rename(
    visit_date_6mo = crf_date 
  ) %>% 
  mutate(
    baby_conception_date = baby_due_date - weeks(40),
    mom_age_6mo_visit = (mom_dob %--% visit_date_6mo) / years(1),
    baby_age_6mo_vsit = (baby_dob %--% visit_date_6mo) / months(1),
    mom_age_conception = (mom_dob %--% baby_conception_date) / years(1),
    mom_age_preg_visit = (mom_dob %--% date_preg) / years(1),
    mom_age_newborn_visit = (mom_dob %--% date_newborn) / years(1),
    mom_age_babydob = (mom_dob %--% baby_dob) / years(1),
    baby_age_newborn_visit = (baby_dob %--% date_newborn) / months(1)
  )

glimpse(dates)

```

```{r}
demo <-
  read_csv(demo_cs_file) %>% 
  select(
    ID = record_id,
    mom_ethnicity, 
    mom_race,
    momrace_describe,
    education,
    educ_describe,
    marital_status,
    marital_explain,
    annual_income,
    ppl_in_home_adults,
    ppl_in_home_allchild,
    child_race,
    childrace_describe,
    child_ethnicity
  ) %>% 
  mutate(
    ID = as.integer(ID),
    ppl_in_home = ppl_in_home_adults + ppl_in_home_allchild
  ) %>% 
  bind_rows(
    read_csv(demo_mom_long_file) %>% 
      select(
        ID = record_id,
        mom_ethnicity, 
        mom_race,
        momrace_describe,
        education,
        educ_describe,
        marital_status,
        marital_explain,
        annual_income,
        ppl_in_home_adults,
        ppl_in_home_allchild
      ) %>% 
      mutate(
        ID = as.integer(ID),
        ppl_in_home = ppl_in_home_adults + ppl_in_home_allchild
      ) %>%
      left_join(
       read_csv(demo_baby_long_file) %>% 
        select(
          ID = record_id,
          baby_sex,
          child_race = baby_race,
          childrace_describe = baby_race_describe,
          child_ethnicity = baby_ethnicity
        ) %>% 
        mutate(
          ID = as.integer(ID)
        )  
      )
  ) %>% 
  left_join(
    read_csv(dob_cs_file) %>% 
        select(
          ID = record_id,
          baby_sex_cs = baby_sex
        ) %>% 
        mutate(ID = as.integer(ID)),
      by = "ID"
  ) %>% 
  mutate(
    household_income = as.character(annual_income),
    household_income_numeric = as.numeric(
      dplyr::recode(
        annual_income,
        "1" = "2500",
        "2" = "10000",
        "3" = "22500",
        "4" = "45000",
        "5" = "75000",
        "6" = "120000",
        "7" = "150000"
      )
    ),
    #santa clara country low-income limit : 80% of median income (ratios <= 1 are therefore "low income")
    #https://www.huduser.gov/portal/datasets/il/il2017/2017summary.odn
    SC_lowincome_limit = as.numeric(
      dplyr::recode(
        ppl_in_home,
        "1" = "59350",
        "2" = "67800",
        "3" = "76300", 
        "4" = "84750",
        "5" = "91500",
        "6" = "98350",
        "7" = "105100",
        "8" = "111900",
        .default = "111900"
      )
    ),
    income_needs = household_income_numeric / SC_lowincome_limit
  )  %>% 
  left_join(
    dates %>% 
      select(ID, contains("age"), baby_dob),
    by = "ID"
  ) %>% 
  mutate(
    baby_sex = if_else(
      is.na(baby_sex),
      baby_sex_cs, baby_sex
    ),
    male = if_else(
      baby_sex == 2,
      1, 0 
    )
  ) %>% 
  select(
    -baby_sex
  ) %>% 
  filter(!is.na(ID))

demo <-
  demo %>% 
  filter(!is.na(mom_ethnicity))

write_csv(demo, "~/Desktop/lena_18mo_symptoms/Data/demographics_20190413.csv")

```



  
    

