---
title: "Score CRISYS"
output: html_notebook
---

```{r}
#Libraries
library(tidyverse)

#Paramaters
#crisys_preg_file <- "~/Desktop/BABIES/r01_winter_2019/data/crisys_preg_20181127.csv"
crisys_preg_file <- "~/Desktop/lena_18mo_symptoms/Data_Final/crisys_preg_20190202.csv"

#crisys_nb_cs_file <- "~/Desktop/BABIES/r01_winter_2019/data/crisys_nb_20181127.csv"
crisys_nb_cs_file <- "~/Desktop/lena_18mo_symptoms/Data_Final/crisys_nb_20190510.csv"

#crisys_6mo_lg_file <- "~/Desktop/BABIES/r01_winter_2019/data/crisys_6mo_lg_20181127.csv" 
crisys_6mo_lg_file <- "~/Desktop/lena_18mo_symptoms/Data_Final/crisys_6mo_long_20190726.csv"

#crisys_6mo_cs_file <- "~/Desktop/BABIES/r01_winter_2019/data/crisys_6mo_cs_20181127.csv" 
crisys_6mo_cs_file <- "~/Desktop/lena_18mo_symptoms/Data_Final/crisys_6mo_cs_20190202.csv"


#Functions
winsorize <- function(df, value) {
  value <- enquo(value)
  
  df %>% 
    mutate(
      value = case_when(
        !! value > (mean(!! value, na.rm = TRUE) + (3*sd(!! value, na.rm = TRUE))) ~
          mean(!! value, na.rm = TRUE) + (3*sd(!! value, na.rm = TRUE)), 
        !! value < (mean(!! value, na.rm = TRUE) - (3*sd(!! value, na.rm = TRUE))) ~
          mean(!! value, na.rm = TRUE) - (3*sd(!! value, na.rm = TRUE)),
        TRUE ~ !! value
      )
    )
}
```

```{r}
crisys <-
  read_csv(crisys_preg_file) %>% 
  rename(ID = record_id) %>% 
  mutate(ID = as.integer(ID)) %>% 
  select(-redcap_survey_identifier:-crisys_timestamp) %>% 
  bind_rows(
    read_csv(crisys_nb_cs_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      select(-redcap_survey_identifier:-crisys_timestamp)
  ) %>% 
  bind_rows(
    read_csv(crisys_6mo_cs_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      select(-redcap_survey_identifier:-crisys_timestamp) 
  ) %>% 
  bind_rows(
    read_csv(crisys_6mo_lg_file) %>% 
      rename(ID = record_id) %>% 
      mutate(ID = as.integer(ID)) %>% 
      select(-redcap_survey_identifier:-crisys_timestamp)
  ) %>% 
  filter(!is.na(crisys_1)) %>% 
  mutate(
    n_crisys = pmap_dbl(
        select(., c(crisys_1:crisys_72)),
        function(...) sum(!is.na(c(...)), na.rm = TRUE)
      ), 
    crisys_total = as.double(
      pmap_dbl(
        select(., c(crisys_1:crisys_72)),
        function(...) mean(c(...), na.rm = TRUE)
      ) * 72
    ) 
  ) %>% 
  select(
    ID,
    timepoint = redcap_event_name,
    crisys_total
  ) %>% 
  mutate(
    timepoint = if_else(
      timepoint == "questionnaires_6mo_arm_1",
      "sixmonth_arm_1", timepoint
    ),
    timepoint = str_remove(timepoint, "_arm_1")
  )

crisys <- 
  winsorize(crisys, crisys_total) %>% 
  rename(crisys_win = value)

```

```{r}
crisys_wf <-
  crisys %>% 
  gather(variable, value, crisys_total:crisys_win) %>% 
  unite(temp, timepoint, variable) %>% 
  spread(temp, value)
```


```{r}
crisys %>% 
  ggplot(aes(timepoint, crisys_total)) +
  geom_line(
    aes(
      timepoint, 
      crisys_total, 
      group = ID
    ),
    color = "blue",
    alpha = 1/4
  ) +
  theme(
    legend.position = "none"
  )

crisys %>% 
  ggplot(aes(timepoint, crisys_total)) +
  geom_boxplot()


crisys %>% 
  ggplot(aes(crisys_total)) +
  geom_histogram() +
  facet_wrap(~timepoint)

crisys %>% 
  ggplot(aes(crisys_win)) +
  geom_histogram() +
  facet_wrap(~timepoint)


```

```{r}
crisys_6mo <-
  crisys_wf %>% 
    select(
      ID,
      crisys_total_6mo = sixmonth_crisys_total
    )
  
crisys_6mo %>% 
  ggplot(aes(crisys_total_6mo)) +
  geom_histogram(bins = 20)

crisys_6mo <- 
  winsorize(crisys_6mo, crisys_total_6mo) %>% 
  rename(crisys_total_6mo_win = value)

crisys_6mo %>% 
  ggplot(aes(crisys_total_6mo_win)) +
  geom_histogram(bins = 20)

write_csv(crisys_6mo, "~/Desktop/lena_18mo_symptoms/Data_Final/crisys_6mo_20190726.csv")
```

```

