---
title: "Score CESD"
author: "Lucy King"
date: "10/10/2018"
output: html_document
---

```{r}
#Libraries
library(tidyverse)
library(psych)

#Parameters
cesd_6mo_cs_file <- "~/Desktop/BABIES/lena_symptoms/data_final/cesd_6mo_cs_20191118.csv"
cesd_6mo_lg_file <- "~/Desktop/BABIES/lena_symptoms/data_final/cesd_6mo_lg_20191118.csv"

cesd_18mo_cs_file <- "~/Desktop/BABIES/lena_symptoms/data_final/qs_18mo_cs_datecleaned_20190726.csv"
cesd_18mo_lg_file <- "~/Desktop/BABIES/lena_symptoms/data_final/qs_18mo_long_datecleaned_20190726.csv"
```

# Read in data 
```{r}
cesd6 <-
  read_csv(
    cesd_6mo_cs_file
  ) %>% 
  bind_rows(
    read_csv(cesd_6mo_lg_file)
  ) %>% 
  filter(cesd_complete == 2) %>% 
  select(
    -redcap_event_name:-cesd_date,
    -cesd_complete
  ) %>% 
  mutate(
    timepoint = "6_month",
    record_id = as.numeric(record_id)
  ) 

```


```{r}
cesd18 <-
  read_csv(
    cesd_18mo_cs_file
  ) %>% 
  select(
    record_id,
    cesd18_1:cesd18_20,
    questionnaires_18mo_complete
  ) %>% 
  filter(questionnaires_18mo_complete == 2) %>% 
  bind_rows(
    read_csv(cesd_18mo_lg_file) %>% 
      select(
        record_id,
        cesd18_1:cesd18_20,
        month_survey_complete
      ) %>% 
      filter(month_survey_complete == 2)
  ) %>% 
  select(-questionnaires_18mo_complete, -month_survey_complete) %>% 
  mutate(timepoint = "18_month") %>% 
  rename_at(
    vars(cesd18_1:cesd18_20),
    funs(
      str_replace(., "18_", "_")
    )
  )
```

```{r}
cesd <-
  cesd6  %>% 
  bind_rows(cesd18) %>% 
  rename(ID = record_id)
```

  
# Score
```{r}
cesd <-
  cesd %>% 
  mutate_at(
    vars(cesd_4, cesd_8, cesd_12, cesd_16),
    funs(
      "r" = 
      . %>%
        dplyr::recode("3" = 0, "2" = 1, "1" = 2, "0" = 3)
    )
  )  %>% 
  group_by(ID, timepoint) %>%
  mutate(
    cesd_total = mean(
      c(
        cesd_1,
        cesd_2,
        cesd_3,
        cesd_4_r,
        cesd_5,
        cesd_6,
        cesd_7,
        cesd_8_r,
        cesd_9,
        cesd_10,
        cesd_11,
        cesd_12_r,
        cesd_13,
        cesd_14,
        cesd_15,
        cesd_16_r,
        cesd_17,
        cesd_18,
        cesd_19,
        cesd_20
      ),
      na.rm = TRUE
    ) * 20
  ) %>% 
  ungroup()

```

# Visualize
```{r}
cesd %>% 
  ggplot(aes(cesd_total)) +
  geom_histogram() +
  geom_vline(aes(xintercept = mean(cesd_total, na.rm = TRUE)), color = "red") +
  facet_wrap(.~fct_rev(timepoint))
```

# reliability

```{r}
cesd6 <-
  cesd %>% 
  filter(timepoint == "6_month")

cesd6 %>% 
  select(
    cesd_1,
    cesd_2,
    cesd_3,
    cesd_4_r,
    cesd_5,
    cesd_6,
    cesd_7,
    cesd_8_r,
    cesd_9,
    cesd_10,
    cesd_11,
    cesd_12_r,
    cesd_13,
    cesd_14,
    cesd_15,
    cesd_16_r,
    cesd_17,
    cesd_18,
    cesd_19,
    cesd_20
  ) %>% 
  alpha()
```

```{r}
cesd18 <-
  cesd %>% 
  filter(timepoint == "18_month")

cesd18 %>% 
  select(
    cesd_1,
    cesd_2,
    cesd_3,
    cesd_4_r,
    cesd_5,
    cesd_6,
    cesd_7,
    cesd_8_r,
    cesd_9,
    cesd_10,
    cesd_11,
    cesd_12_r,
    cesd_13,
    cesd_14,
    cesd_15,
    cesd_16_r,
    cesd_17,
    cesd_18,
    cesd_19,
    cesd_20
  ) %>% 
  alpha()
```

```{r}
write_csv(cesd6, "~/Desktop/BABIES/lena_symptoms/data_final/cesd_6mo_scored_20191118.csv")
write_csv(cesd18, "~/Desktop/BABIES/lena_symptoms/data_final/cesd_18mo_scored_20191118.csv")
```

